export const Types = {
    UUID(): UUID {
        return {
            type: "UUID",
        };
    },
    STRING(size?: number): STRING {
        return { type: "STRING", size: size ?? 255 };
    },
    INTEGER(): INTEGER {
        return { type: "INTEGER" };
    },
    FLOAT(): FLOAT {
        return { type: "FLOAT" };
    },
    REFERENCE<T extends string>(tableName: T): REFERENCE<T> {
        return {
            type: "REFERENCE",
            referencedTable: tableName,
        };
    },
} as const;

export type STRING = {
    type: "STRING";
    indexed?: boolean;
    nullable?: boolean;
    size: number;
};

export type INTEGER = {
    type: "INTEGER";
    min?: number;
    max?: number;
    indexed?: boolean;
    nullable?: boolean;
};

export type FLOAT = {
    type: "FLOAT";
    min?: number;
    max?: number;
    indexed?: boolean;
    nullable?: boolean;
};

export type UUID = {
    type: "UUID";
    nullable?: boolean;
    primaryKey?: boolean;
    autogenerated?: boolean;
};

export type REFERENCE<T extends string> = {
    type: "REFERENCE";
    referencedTable: T;
};

export type TypescriptTypeOf<T> = T extends UUID
    ? string
    : T extends STRING
    ? string
    : T extends REFERENCE<string>
    ? string
    : T extends INTEGER
    ? number
    : T extends FLOAT
    ? number
    : never;

export type SchemaTypes<TableNames extends string> =
    | UUID
    | STRING
    | INTEGER
    | FLOAT
    | REFERENCE<TableNames>;
