import type { UnionToIntersection } from "@fabric/core";
import {
  AlreadyExistsError,
  NotFoundError,
  UnexpectedError,
  type ClassConstructor,
} from "@fabric/core";
import type { ScheduledUseCaseDependencies } from "./schedules.js";
import {
  ExpiredTokenError,
  InvalidTokenError,
} from "./services/auth-service.js";
import {
  AddModuleToCourseUseCase,
  AddQuestionnaireResponseUseCase,
  AddQuestionnaireSectionToUnitUseCase,
  AddResourceToCourseUseCase,
  AddTagToResourceUseCase,
  AddTagToUnitUseCase,
  AddTextSectionToUnitUseCase,
  AddUnitToModuleUseCase,
  AddVideoSectionToUnitUseCase,
  BatchEnrollmentFailedError,
  CancelInviteUseCase,
  ChangeCourseDescriptionUseCase,
  ChangeCourseTitleUseCase,
  ChangeModuleOrderUseCase,
  ChangeModuleTitleUseCase,
  ChangeUnitOrderUseCase,
  ChangeUnitTitleUseCase,
  CloneCourseUseCase,
  CourseNotFoundError,
  CreateCourseUseCase,
  CreateTagUseCase,
  DeleteModuleUseCase,
  DeleteQuestionnaireSectionUseCase,
  DeleteTextSectionUseCase,
  DeleteUnitUseCase,
  DeleteVideoSectionUseCase,
  EditQuestionnaireSectionContentUseCase,
  EditResourceUseCase,
  EditTextSectionContentUseCase,
  EditVideoSectionContentUseCase,
  EmptyCourseError,
  EnrollStudentInCourseUseCase,
  EnrollUsersByEmailUseCase,
  GetAllCoursesUseCase,
  GetCourseDetailsUseCase,
  GetCourseEnrollmentsUseCase,
  GetCurrentUserUseCase,
  GetDetailedStudentProgressUseCase,
  GetProgressByModuleUseCase,
  GetQuestionnaireResponseUseCase,
  GetResourcesByUnitTagsUseCase,
  GetTagsUseCase,
  GetUnitWithSectionsUseCase,
  IncompleteQuestionnaireResponseError,
  InvalidCredentialsError,
  InvalidInviteCodeError,
  InvalidPasswordResetTokenError,
  InviteUserUseCase,
  ListUserInvitesUseCase,
  ListUsersUseCase,
  LoginUseCase,
  ModuleNotFoundError,
  NotEnrolledInCourseError,
  QuestionnaireResponseNotFoundError,
  QuestionnaireSectionNotFoundError,
  QuestionnaireVersionMismatchError,
  RegisterUserUseCase,
  RequestPasswordResetUseCase,
  ResendInviteUseCase,
  ResetPasswordUseCase,
  ResourceNotFoundError,
  StudentAlreadyEnrolledError,
  TagAlreadyExistsError,
  TextSectionNotFoundError,
  UnitNotFoundError,
  UserAlreadyExistsError,
  UserAlreadyInvitedError,
  UserNotFoundError,
  VideoSectionNotFoundError,
} from "./use-cases/index.js";
import type {
  UseCaseDependencies,
  UseCaseErrorValue,
} from "./utils/use-case.js";
import { UnauthorizedError } from "./utils/use-case.js";

export const DomainUseCases = [
  LoginUseCase,
  InviteUserUseCase,
  CreateCourseUseCase,
  AddModuleToCourseUseCase,
  AddUnitToModuleUseCase,
  ChangeCourseTitleUseCase,
  ChangeCourseDescriptionUseCase,
  ChangeModuleOrderUseCase,
  ChangeUnitOrderUseCase,
  EnrollStudentInCourseUseCase,
  EnrollUsersByEmailUseCase,
  GetAllCoursesUseCase,
  GetCourseDetailsUseCase,
  GetUnitWithSectionsUseCase,
  CreateTagUseCase,
  GetResourcesByUnitTagsUseCase,
  AddQuestionnaireResponseUseCase,
  GetQuestionnaireResponseUseCase,
  AddTextSectionToUnitUseCase,
  AddVideoSectionToUnitUseCase,
  AddQuestionnaireSectionToUnitUseCase,
  RegisterUserUseCase,
  GetTagsUseCase,
  ChangeModuleTitleUseCase,
  GetCurrentUserUseCase,
  ListUsersUseCase,
  ListUserInvitesUseCase,
  ChangeUnitTitleUseCase,
  EditVideoSectionContentUseCase,
  EditTextSectionContentUseCase,
  EditQuestionnaireSectionContentUseCase,
  GetCourseEnrollmentsUseCase,
  AddResourceToCourseUseCase,
  EditResourceUseCase,
  AddTagToResourceUseCase,
  AddTagToUnitUseCase,
  RequestPasswordResetUseCase,
  ResetPasswordUseCase,
  ResendInviteUseCase,
  CancelInviteUseCase,
  GetDetailedStudentProgressUseCase,
  GetProgressByModuleUseCase,
  DeleteModuleUseCase,
  DeleteUnitUseCase,
  DeleteQuestionnaireSectionUseCase,
  DeleteVideoSectionUseCase,
  DeleteTextSectionUseCase,
  CloneCourseUseCase,
] as const;

export type DomainUseCases = typeof DomainUseCases;

export type DomainUseCaseErrors =
  | UseCaseErrorValue<DomainUseCases[number]>
  | InvalidTokenError
  | UnauthorizedError
  | ExpiredTokenError;

export const DomainUseCaseErrorsMap = {
  UnexpectedError: UnexpectedError,
  InvalidCredentialsError: InvalidCredentialsError,
  UserAlreadyExistsError: UserAlreadyExistsError,
  UserAlreadyInvitedError: UserAlreadyInvitedError,
  CourseNotFoundError: CourseNotFoundError,
  ModuleNotFoundError: ModuleNotFoundError,
  StudentAlreadyEnrolledError: StudentAlreadyEnrolledError,
  BatchEnrollmentFailedError: BatchEnrollmentFailedError,
  NotEnrolledInCourseError: NotEnrolledInCourseError,
  UnitNotFoundError: UnitNotFoundError,
  TagAlreadyExistsError: TagAlreadyExistsError,
  QuestionnaireSectionNotFoundError: QuestionnaireSectionNotFoundError,
  QuestionnaireVersionMismatchError: QuestionnaireVersionMismatchError,
  IncompleteQuestionnaireResponseError: IncompleteQuestionnaireResponseError,
  QuestionnaireResponseNotFoundError: QuestionnaireResponseNotFoundError,
  InvalidInviteCodeError: InvalidInviteCodeError,
  InvalidTokenError: InvalidTokenError,
  ExpiredTokenError: ExpiredTokenError,
  UnauthorizedError: UnauthorizedError,
  EmptyCourseError: EmptyCourseError,
  UserNotFoundError: UserNotFoundError,
  ResourceNotFoundError: ResourceNotFoundError,
  TagNotFoundError: ResourceNotFoundError,
  AlreadyExistsError: AlreadyExistsError,
  InvalidPasswordResetTokenError: InvalidPasswordResetTokenError,
  NotFoundError: NotFoundError,
  TextSectionNotFoundError: TextSectionNotFoundError,
  VideoSectionNotFoundError: VideoSectionNotFoundError,
} as const satisfies Record<
  DomainUseCaseErrors["_tag"],
  ClassConstructor<DomainUseCaseErrors>
>;
export type DomainUseCaseErrorsMap = typeof DomainUseCaseErrorsMap;

export type DomainDependencies = Omit<
  UnionToIntersection<
    UseCaseDependencies<DomainUseCases[number]> | ScheduledUseCaseDependencies
  >,
  "currentUser"
>;
